#include "cuda/kernels/hopper/b_presum_kernel/hopper_f16_sw_a_presum_interleaved_b_presum_kernel_cooperative_max_fusion_tma_reduce.cuh"
#include "cuda/kernels/hopper/b_presum_kernel/kernel_runner_support.cuh"

STRASSEN_RUNNER_EXPORT_B_PRESUM_KERNEL(run_hopper_f16_sw_a_presum_interleaved_b_presum_kernel_cooperative_max_fusion_tma_reduce_2x256_2x256_opt_no, HopperF16APresumInterleavedBPresumKernelCooperativeMaxFusionTmaReduce_2x256_2x256_OptNo)
STRASSEN_RUNNER_EXPORT_B_PRESUM_KERNEL(run_hopper_f16_sw_a_presum_interleaved_b_presum_kernel_cooperative_max_fusion_tma_reduce_2x256_2x256_opt_0000, HopperF16APresumInterleavedBPresumKernelCooperativeMaxFusionTmaReduce_2x256_2x256_Opt_0000)