#include "cuda/kernels/hopper/strassen_winograd/hopper_f16_sw_interleaved_presum_cooperative_pingpong_max_fusion_tma_reduce.cuh"
#include "cuda/kernel_runner_support.cuh"

STRASSEN_RUNNER_EXPORT_CUTLASS3(run_hopper_f16_sw_interleaved_presum_cooperative_pingpong_max_fusion_tma_reduce_2x256_2x256_opt_no, HopperF16InterleavedPresumCooperativePingpongMaxFusionTmaReduce_2x256_2x256_OptNo)
STRASSEN_RUNNER_EXPORT_CUTLASS3(run_hopper_f16_sw_interleaved_presum_cooperative_pingpong_max_fusion_tma_reduce_2x256_2x256_opt_0000, HopperF16InterleavedPresumCooperativePingpongMaxFusionTmaReduce_2x256_2x256_Opt_0000)
STRASSEN_RUNNER_EXPORT_CUTLASS3(run_hopper_f16_sw_interleaved_presum_cooperative_pingpong_max_fusion_tma_reduce_4x256_4x256_opt_no, HopperF16InterleavedPresumCooperativePingpongMaxFusionTmaReduce_4x256_4x256_OptNo)